CXXFLAGS = -g3 -Wall --pedantic -std=c++11

esercizio3.0: esercizio3.0.cpp funzioni.h Vettore.h
	g++ esercizio3.0.cpp -o esercizio3.0 $(CXXFLAGS)

clean: 
	@rm -rf esercizio3.0.dSYM
	@rm -f esercizio3.0
	@rm -f 19410.txt